version: '3.9'

services:
  frontend:
    image: ghcr.io/scout-ch/thilo/thilo_frontend:latest
    restart: always
    environment:
      - BACKEND_URL=http://localhost:3031
    ports:
      - 3030:3000

  backend:
    image: ghcr.io/scout-ch/thilo-api/thilo_api:latest
    restart: always
    networks:
      - internal
    ports:
      - 3031:1337
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
      - CLOUDINARY_NAME=
      - CLOUDINARY_KEY=
      - CLOUDINARY_SECRET=
      - DATABASE_HOST=database
      - DATABASE_NAME=strapi
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin

  linkshortner:
    image: ghcr.io/scout-ch/thilo-shortener/thilo_shortener:latest
    restart: always
    ports:
      - 8080:80

  feedback:
    image: getfider/fider:main
    restart: always
    networks:
      - internal
    ports:
      - 9000:3000
    depends_on:
      - database
    environment:
      BASE_URL: http://localhost:9000

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://postgres:admin@database:5432/fider?sslmode=disable

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE

      # From which account e-mails will be sent
      EMAIL_NOREPLY: noreply@thilo.scout.ch

      ###
      # EMAIL
      ###
      EMAIL_SMTP_HOST: smtp.sendgrid.net
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USERNAME: apikey
      EMAIL_SMTP_PASSWORD: apikiey
      EMAIL_SMTP_ENABLE_STARTTLS: 'true'

  database:
    image: postgres:16.0
    restart: always
    networks:
      - internal
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: always
    networks:
      - internal
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thilo.ch
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  internal:

volumes:
  postgres:
  pgadmin:
