name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Build and Push Thilo Container
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker container
        uses: docker/build-push-action@v3
        with:
          context: ./
          load: true
          tags: |
            ghcr.io/scout-ch/thilo/thilo_frontend:latest
      - name: Push docker container
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          tags: |
            ghcr.io/scout-ch/thilo/thilo_frontend:latest

  build:
    name: Build Thilo App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-cache
          path: ./dist

  deploy:
    name: Deploy Thilo App
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-cache
          path: ./dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
