name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Thilo App Prod
    runs-on: ubuntu-latest
    env:
      REACT_APP_PUBLIC_URL: /
      BACKEND_URL: https://api.thilo.scouts.ch/

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Create backend export
        run: node src/scripts/strapiToJson.js
      - run: npm run build
      - run: echo "$(envsubst < build/index.html)" > build/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: build-cache-prod
          path: ./build
